spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:../../config-repo,file:../config-repo,file:./config-repo,file:../../../config-repo
server:
  port: 8888
