spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: 192.168.43.131
    port: 6380
  datasource:
    url: jdbc:mysql:///warpexchange?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
logging:
  level:
    root: INFO
eureka:
  server:
    port: 8001
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.server.hostname}:${eureka.server.port}/eureka/
time:
  zone-id: GMT+8
batchCount: 1